### PR TITLE
Limit certain features to a subset of projects

### PR DESCRIPTION
**Pull request by tmartyny**
All tests pass.
Some teams don't want these features.selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by lillieatwork** [comment]
Someday it'd be cool to have this kind of thing be a feature (where the data lives in the DB), but I accept the pragmatism of constants with strings in the code.

**Comment by franckverrot** [comment]
@lillieatwork +1 . We had talks about releasing Wattle as an OSS product and such changes make it very Omada-specific. 

@cconstantine wdyt?

**Comment by mpg916** [comment]
@tmartyny @Kooshaba - @franckverrot's comment is correct in not having Omada specific references in the code. There's two ways to go about this to satisfy that requirement:
1. Change the constant to a variable/secret that we load from consul.
2. Follow the pattern of `_filters` columns on the `watchers` so that we can specify "features" that we want triggered on/off. The features could then be generically named (i.e. PT auto language labeling feature) without any reference to Omada.

**Comment by tmartyny** [comment]
🤣

**Pull request closed without merging**
